#!/usr/bin/env python3
"""Regenerate board-data.js and rankings.csv. Never touches draft-board-2026.html."""
import json, subprocess, sys, datetime, pathlib, csv
HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent

for step in ("score.py", "fit.py", "board.py", "dad_score.py", "dad_board.py"):
    print(f"--- {step}")
    subprocess.run([sys.executable, step], cwd=HERE, check=True)

rows = json.load(open(HERE / "board_out.json"))
dad_rows = json.load(open(HERE / "dad_board_out.json"))
if len(rows) < 150:
    sys.exit(f"ABORT: only {len(rows)} players — something upstream broke. Not overwriting.")
if len(dad_rows) != len(rows):
    sys.exit("ABORT: Dad profile player count differs from the main board. Not overwriting.")

# A live inactive designation paired with full-season availability is a stale
# judgement, not a harmless warning. Refuse to publish until players.py is
# updated deliberately; the previous behavior silently shipped bad ranks.
inactive = {"IR", "PUP", "Out", "Sus", "NA", "DNR", "Doubtful"}
conflicts = [x for x in rows if x.get("inj") in inactive and x.get("av", 1) >= 1
             and x.get("tot") is not None]
if conflicts:
    names = ", ".join(f"{x['p']} ({x['inj']})" for x in conflicts)
    sys.exit(f"ABORT: live injury status conflicts with full availability: {names}. "
             "Update avail in refresh/players.py; generated files were not overwritten.")

sys.path.insert(0, str(HERE))
import sources  # noqa: E402 - local module, loaded after the pipeline succeeds
sources.load(quiet=True)
source_meta = sources.LAST_META

def abort(message):
    sys.exit(f"ABORT: {message}. Generated files were not overwritten.")

if [x["rk"] for x in rows] != list(range(1, len(rows) + 1)):
    abort("ranks are not unique and sequential")
if len({(x["p"], x["tm"], x["pos"]) for x in rows}) != len(rows):
    abort("duplicate player identities found")
if min(x["rk"] for x in rows if x["pos"] == "DST") < 145:
    abort("a defense escaped the round-13 floor")
if min(x["rk"] for x in rows if x["pos"] == "K") < 169:
    abort("a kicker escaped the round-15 floor")
if [x["rk"] for x in dad_rows] != list(range(1, len(dad_rows) + 1)):
    abort("Dad profile ranks are not unique and sequential")
if min(x["rk"] for x in dad_rows if x["pos"] == "DST") < 141:
    abort("a Dad-profile defense escaped the round-15 floor")
if min(x["rk"] for x in dad_rows if x["pos"] == "K") < 161:
    abort("a Dad-profile kicker escaped the round-17 floor")
if sum(x.get("tot") is None for x in dad_rows) > sum(x.get("tot") is None for x in rows):
    abort("Dad profile lost scoring coverage for projected players")
expert_rows = [x for x in rows if x.get("expert_lane") is not None]
if len(expert_rows) < 80:
    abort("expert ranking coverage fell below 80 players")
expert_top = sorted(expert_rows, key=lambda x: x["expert_lane"])[:75]
if any(x["pos"] in ("K", "DST") for x in expert_top):
    abort("expert source looks like a points list: K/DST found in its top 75")
if sum(x["pos"] == "QB" for x in expert_top[:25]) > 4:
    abort("expert source looks like superflex: too many QBs in its top 25")
for key in ("ffc", "rotoballer", "injuries"):
    health = source_meta.get(key, {})
    if health.get("status") == "missing":
        abort(f"required source {key} is missing")
    if health.get("age_hours") is not None and health["age_hours"] > 48:
        abort(f"required source {key} is more than 48 hours old")

stamp = datetime.date.today().strftime("%d %B %Y").lstrip("0")
meta = {"generated": stamp, "players": len(rows), "sources": source_meta,
        "profiles": {"sleeper": {"label": "Sleeper league", "teams": 12, "rounds": 16},
                     "dad": {"label": "Dad's league", "teams": 10, "rounds": 18}}}
(ROOT / "board-data.js").write_text(
    "// Generated by refresh/build.py. Safe to overwrite on every refresh.\n"
    "// Do NOT hand-edit: presentation changes belong in draft-board-2026.html.\n"
    f"window.BOARD_META = {json.dumps(meta)};\n"
    f"window.BOARD_PROFILES = {json.dumps({'sleeper': rows, 'dad': dad_rows}, separators=(',',':'))};\n"
    "window.BOARD_DATA = window.BOARD_PROFILES.sleeper;\n")

N = lambda v: "NR" if v is None else v
with open(ROOT / "rankings.csv", "w", newline="") as f:
    # Keep the generated file Unix-friendly so git diffs stay readable.
    w = csv.writer(f, lineterminator="\n")
    w.writerow(["Rank","OverallTier","Pos","PosTier","Player","Team","Bye","Tag",
      "MarketADP","ExpertRank","FantasyCalc","FFCHalfPPR","YahooADP","ESPNpprADP",
      "NumSignals","DecisionAnchor","Spread",
      "ModelRank","Gap","AwardOdds","LeaguePts","YardBonusPts","Injury","InjuryBody","GreenFlag","RedFlag"])
    for x in rows:
        w.writerow([x["rk"],x["otier"],x["pos"],x["ptier"],x["p"],x["tm"],x["bye"],x["tag2"],
          N(x["market"]),N(x["expert_lane"]),N(x["fcalcr"]),N(x["ffcr"]),N(x["yahoor"]),
          N(x["espnr"]),x["nsrc"],x["anchor"],x["spread"],
          N(x["model"]),x["gap"],x["mktnote"],round(x["tot"],1) if x["tot"] else "",x["bonus"],N(x["inj"]),N(x["injbody"]),x["g"],x["r"]])

print(f"\nboard-data.js + rankings.csv — 2 profiles, {len(rows)} players each, stamped {stamp}")
