#!/usr/bin/env python3
"""Regenerate board-data.js and rankings.csv. Never touches draft-board-2026.html."""
import json, subprocess, sys, datetime, pathlib, csv
HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent

for step in ("score.py", "fit.py", "board.py"):
    print(f"--- {step}")
    subprocess.run([sys.executable, step], cwd=HERE, check=True)

rows = json.load(open(HERE / "board_out.json"))
if len(rows) < 150:
    sys.exit(f"ABORT: only {len(rows)} players — something upstream broke. Not overwriting.")

stamp = datetime.date.today().strftime("%d %B %Y").lstrip("0")
(ROOT / "board-data.js").write_text(
    "// Generated by refresh/build.py. Safe to overwrite on every refresh.\n"
    "// Do NOT hand-edit: presentation changes belong in draft-board-2026.html.\n"
    f"window.BOARD_META = {json.dumps({'generated': stamp, 'players': len(rows)})};\n"
    f"window.BOARD_DATA = {json.dumps(rows, separators=(',',':'))};\n")

N = lambda v: "NR" if v is None else v
with open(ROOT / "rankings.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Rank","OverallTier","Pos","PosTier","Player","Team","Bye","Tag","Sleeper","ESPN",
      "FantasyProsECR","FProsTier","Flock","AvgPublic","Spread","ModelRank","Gap","Market",
      "PropLine","ProjVsLinePct","TeamWinTotal","AwardOdds","ScoringFit","LeaguePts","YardBonusPts",
      "GreenFlag","RedFlag"])
    for x in rows:
        w.writerow([x["rk"],x["otier"],x["pos"],x["ptier"],x["p"],x["tm"],x["bye"],x["tag2"],
          N(x["sl"]),N(x["es"]),N(x["fpr"]),N(x["fpt"]),N(x["fkr"]),x["avg"],x["spread"],
          N(x["model"]),x["gap"],x["mkt"],N(x["prop"]),N(x["propdelta"]),x["win"],x["mktnote"],
          N(x["fit"]),round(x["tot"],1) if x["tot"] else "",x["bonus"],x["g"],x["r"]])

print(f"\nboard-data.js + rankings.csv — {len(rows)} players, stamped {stamp}")
